apiVersion: v1
kind: Service
metadata:
  name: {{ include "consul.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consul.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      name: http
    - port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      name: grpc
    - port: {{ .Values.service.ports.dns }}
      targetPort: dns
      protocol: UDP
      name: dns
  selector:
    {{- include "consul.selectorLabels" . | nindent 4 }}
    component: server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "consul.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "consul.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 8500
      name: http
    - port: 8301
      name: serflan
    - port: 8302
      name: serfwan
    - port: 8300
      name: server
  selector:
    {{- include "consul.selectorLabels" . | nindent 4 }}
    component: server
