---
# Handlers for apps role

- name: Restart vault
  ansible.builtin.command: kubectl rollout restart statefulset vault -n service
  delegate_to: localhost

- name: Restart authentik
  ansible.builtin.command: kubectl rollout restart deployment authentik-server -n service
  delegate_to: localhost

- name: Restart gitlab
  ansible.builtin.command: kubectl rollout restart deployment gitlab-webservice-default -n code
  delegate_to: localhost
