{{- if .Values.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zerobyte.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zerobyte.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode }}
  storageClassName: {{ .Values.persistence.config.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
{{- end }}
---
{{- if .Values.persistence.cache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zerobyte.fullname" . }}-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zerobyte.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.cache.accessMode }}
  storageClassName: {{ .Values.persistence.cache.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size }}
{{- end }}
