apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: {{ .Release.Namespace }}
data:
  vault.hcl: |
    ui = true
    disable_mlock = true

    listener "tcp" {
      address = "[::]:8200"
      cluster_address = "[::]:8201"
      tls_disable = true
    }

    # Integrated Storage (Raft)
    storage "raft" {
      path    = "/vault/data"
      node_id = "vault-0"
    }

    api_addr = "http://vault.{{ .Release.Namespace }}.svc.cluster.local:8200"
    cluster_addr = "http://vault-0.vault-internal.{{ .Release.Namespace }}.svc.cluster.local:8201"

    {{- if .Values.consul.enabled }}
    # Consul Service Registration
    service_registration "consul" {
      address      = "{{ .Values.consul.host }}"
      service      = "vault"
      service_tags = "vault"
      check_interval = "10s"
      check_timeout = "5s"
    }
    {{- end }}
