{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.admin.user | quote }}
  admin-password: {{ .Values.grafana.admin.password | quote }}
  {{- if .Values.grafana.oidc.enabled }}
  oidc-client-id: {{ .Values.grafana.oidc.clientId | quote }}
  oidc-client-secret: {{ .Values.grafana.oidc.clientSecret | quote }}
  {{- end }}
{{- end }}
