---
- name: Host Setup
  hosts: local
  become: false
  gather_facts: true
  tags: [setup_host]
  roles:
    - role: setup_host
      tags: [setup_host, homebrew, dependencies, ssh, verify]

- name: kubernetes
  hosts: local
  become: false
  gather_facts: true
  tags: [kubespray, kubernetes]
  roles:
    - role: kubespray
      tags: [kubernetes, kubespray]

- name: Master Node Configuration
  hosts: masters
  become: true
  gather_facts: true
  tags: [master, deploy]
  roles:
    - role: server
      tags: [server]
    - role: docker
      tags: [docker]
    - role: apps
      tags: [apps]
    - role: pangolin
      tags: [pangolin]
      vars:
        pangolin_mode: node

- name: Worker Nodes Configuration
  hosts: workers
  become: true
  gather_facts: true
  tags: [worker, deploy]
  roles:
    - role: server
      tags: [server]
    - role: docker
      tags: [docker]
    - role: apps
      tags: [apps]
    - role: pangolin
      tags: [pangolin]
      vars:
        pangolin_mode: node

- name: Gateway Configuration
  hosts: gateway
  become: true
  gather_facts: true
  tags: [gateway, deploy]
  roles:
    - role: server
      tags: [server]
    - role: docker
      tags: [docker]
    - role: apps
      tags: [apps]
    - role: pangolin
      tags: [pangolin]
      vars:
        pangolin_mode: gateway
