---
- name: Host
  hosts: local
  become: false
  gather_facts: true
  tags: [setup_host]
  roles:
    - role: setup_host
      tags: [setup_host, homebrew, dependencies, ssh, verify]

- name: Master
  hosts: master
  gather_facts: true
  tags: [master, deploy]
  roles:
    - role: server
    - role: docker
    - role: kubespray
      tags: master
      type: node
    - role: apps
      tags: master
    - role: pangolin
      tags: node

- name: Worker
  hosts: workers
  gather_facts: true
  tags: [worker, deploy]
  roles:
    - role: server
    - role: docker
    - role: kubespray
      tags: worker
      type: node
    - role: apps
      tags: worker
    - role: pangolin
      tags: node

- name: Gateway
  hosts: gateway
  gather_facts: true
  tags: [gateway, deploy]
  roles:
    - role: server
    - role: docker
    - role: kubespray
      tags: worker
      type: gateway
    - role: apps
      tags: gateway
    - role: pangolin
      tags: gateway
