---
repositories:
  # Storage
  - name: openebs
    url: https://openebs.github.io/openebs

  # Container Registry
  - name: harbor
    url: https://helm.goharbor.io

  # Ingress & Networking
  - name: traefik
    url: https://traefik.github.io/charts

  # Certificates
  - name: jetstack
    url: https://charts.jetstack.io

  # Authentication
  - name: authentik
    url: https://charts.goauthentik.io

  # Databases (Bitnami OCI)
  - name: bitnami
    oci: true
    url: registry-1.docker.io/bitnamicharts

  # GitLab
  - name: gitlab
    url: https://charts.gitlab.io

  # Productivity
  - name: penpot
    url: https://helm.penpot.app

  # Automation
  - name: kestra
    url: https://helm.kestra.io

  # DevOps
  - name: devtron
    url: https://helm.devtron.ai
