apps:
  # BASE

  namespaces:
    repo: charts
    chart: namespaces
    namespace: default
    version: v1.0.0

  # INGRESS

  traefik:
    repo: traefik
    chart: traefik
    namespace: ingress
    version: v37.2.0
    createNamespace: true

  cert-manager:
    repo: jetstack
    chart: cert-manager
    version: v1.19.1
    namespace: service
    needs:
      - service/vault

  # AI
  openclaw:
    repo: charts
    chart: openclaw
    namespace: automation
    version: v1.0.0
    needs:
      - ingress/traefik
      - service/cert-manager
      - service/authentik
      - service/vault
