apiVersion: v2
name: vert
description: A Helm chart for VERT - File converter service (rendered by chart-base)
type: application
version: 1.0.0
appVersion: "latest"
keywords:
  - vert
  - converter
  - files
  - utilities
home: https://vert.sh
sources:
  - https://github.com/VERT-sh/VERT
maintainers:
  - name: ZeiZel
    email: valera2003lvov@yandex.ru
dependencies:
  - name: chart-base
    version: 0.1.0
    repository: file://../../chart-base
