{{- range $sec := .Values.secrets }}
{{- $top := $ }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-base.childname" (list $top $sec.name) }}
  namespace: {{ $top.Release.Namespace }}
  labels:
    {{- include "chart-base.labels" $top | nindent 4 }}
  {{- with $sec.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ $sec.type | default "Opaque" }}
{{- with $sec.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with $sec.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
